matrix:
  include:
  - language: node_js
    node_js:
      - "8"
    before_script:
      - cd admin-ui
    script:
      - ls
  - language: node_js
    node_js:
      - "8"
    before_script:
      - cd mail-box
    script:
      - ls
  - language: node_js
    node_js:
      - "8"
    before_script:
      - cd user-management
    script:
      - ls